### PR TITLE
add test for reading Hamiltonian from wannier90 output

### PR DESCRIPTION
**Pull request by nils-wittemeier**
Add test for the reading of Wannier90 Hamiltonian in sisl. See related PR in sisl-files repo  ([sisl-files #11](https://github.com/zerothi/sisl-files/pull/11)).

### CODE REVIEW

**Comment by zerothi** [comment]
Once the other PR is merged, then you should bump the files submodule in this PR as well. :)

Thanks!

**Comment by zerothi** [comment]
The `files` folder is a submodule (git-terminology).
So you should do something like this:
```shell
cd <root sisl folder>
git submodule init # if files doesn't already exist and is populated
cd files
git pull
cd ..
git add files
```

**Comment by zerothi** [comment]
think of the `files` submodule as a regular file in the repo

**Comment by nils-wittemeier** [comment]
I am not sure, why this is showing a merge conflict now.

Maybe I went wrong in updating the submodule?

**Comment by zerothi** [comment]
I'll amend to this branch to try and fix it... I can't immediately see what went wrong, I'll ping you, thanks!

**Comment by zerothi** [comment]
It was because your branch was way behind `main`, then the submodule thing has problems. A simple rebase solved the problem.

**Pull request merged**
