### PR TITLE
Fix issue 486 - in correct sign of the y component of the spin moments

### PR DESCRIPTION
**Pull request by juijan**
Fix issue #486 - in correct sign of the y component of the spin moments

### CODE REVIEW

**Comment by zerothi** [comment]
Did you check with siesta values?

**Comment by zerothi** [comment]
I added a new commit which also fixes PDOS calculation. :)

Could you have a look?

**Comment by juijan** [comment]
The commit for the PDOS calculations looks good to me.

**Comment by zerothi** [comment]
Thanks!!

Next time, please ensure you have a clean *main*, i.e. your main was several commits behind :)

**Pull request merged**
