### PR TITLE
Function to translate atoms in geometry into the unit cell

### PR DESCRIPTION
**Pull request by tfrederiksen**
Through my work with the surface slabs I think it would be convenient with a function that translates atoms (if outside) into the unit cell. I think similar algorithms are already in use internally. This PR offers this as a new function `translate2uc`.

### CODE REVIEW

**Comment by zerothi** [comment]
Great, thanks!

Could you comment on the importance of the `tol` parameter?

I will just commit here an addition to allow doing this for individual lattice vectors.

**Comment by zerothi** [comment]
Regarding the `tol` I also have some tolerances here and there, but I am just afraid they'll be wrongly applied. Consider a system with a lattice vector of 1000 A and a tolerance of 1e-5 means a physical shift of 0.01 Ang...

**Comment by zerothi** [comment]
Hmm, as it stands I am probably more in favour of removing the `tol`, parameter? Would this be ok, or are there issues with this?

**Comment by tfrederiksen** [comment]
> Hmm, as it stands I am probably more in favour of removing the `tol`, parameter? Would this be ok, or are there issues with this?

OK, I agree this will be cleaner. Eventually the users can, if necessary, apply the small shift before and after the function call.

**Comment by tfrederiksen** [comment]
Don't you think we could insert an optional offset to this method?
```python
def translate2uc(..., offset=None):
    if isinstance(offset, float):
        d = np.ones(3) * offset
    elif isinstance(offset, list):
        d = np.array(offset)
    else:
        d = np.zeros(3)
    g = g.move(d)
    # do the existing stuff in this function
    g = g.move(-d)
    return g
```

**Comment by zerothi** [comment]
I think we should first create a few more test cases to see if there are better routes, I have thought about:
- small shifts
- using round with a "number of significant digits"
- instead of using fractional cells, then use a normalized fractional cell such that all numerics are done on the same scale

To solve this I would rather collect the set of difficult problems before trying to attack it without realizing what the root cause is.

**Comment by tfrederiksen** [comment]
OK, what about leaving this as a pending issue then?

**Pull request merged**
