### PR TITLE
Fix the basis when reading from XV

### PR DESCRIPTION
**Pull request by pfebrer**
When reading the geometry from an XV file using `fdf.read_geometry(output=True)`, the basis was not correctly set. It was completely broken, I don't know why I (or anyone) hadn't noticed until now :sweat_smile:

### CODE REVIEW

**Comment by pfebrer** [comment]
Minimal example:

[XV_fail.zip](https://github.com/zerothi/sisl/files/15475837/XV_fail.zip)

**Comment by tfrederiksen** [comment]
I can confirm this issue. For one of my systems I find: 
```
# read from fdf
g = sisl.get_sile("./RUN.fdf").read_geometry()
print(g.atoms.atom)
[<sisl.Atom H.opt88, Z=1, M=1.01, maxR=2.8520000000000043, no=5>, 
 <sisl.Atom Au.blyp, Z=79, M=196.97, maxR=3.328400000000018, no=15>,
 <sisl.Atom Aus.blyp, Z=79, M=196.97, maxR=4.7660999999999865, no=16>,
 <sisl.Atom C.blyp, Z=6, M=12.01, maxR=2.954100000000009, no=13>]

# read from XV
g = sisl.get_sile("./RUN.fdf").read_geometry(True)
print(g.atoms.atom)
[<sisl.Atom H.opt88, Z=1, M=1.01, maxR=2.8520000000000043, no=5>,
 <sisl.Atom Li, Z=3, M=6.941, maxR=-1.0, no=1>]
```
The first case has the correct atoms (and input coordinates), the latter wrong atoms (but correct, relaxed coordinates).

**Comment by pfebrer** [comment]
Actually the fix here isn't fully correct either. 

It seems that using `species_as_Z` is not a good idea. When reading from the fdf file the atoms list is not sorted by species index but by appearance.

So something like:

```
In the fdf file

Species:
1 Au
2 O

Coordinates:
X X X 2
X X X 1
```

```
In the XV file

Coordinates:
2 8   X X X
1 79 X X X
```

Will lead to reversed species if you read from `fdf.read_geometry(output=True)`

So either:
   - Species must be sorted when reading the basis from fdf.
   - Atoms from the XV file must be retreived from the basis based on their atomic number, not their index.

I think the second one makes more sense, but I don't know if other files that use `_replace_with_species` also contain the atomic numbers.

**Comment by pfebrer** [comment]
Hmm getting the basis by Z won't work either if you have multiple atoms with the same Z, as Thomas' example :sweat_smile: 

So the only option is that `fdf.read_basis()` returns the atoms sorted by species.

**Comment by pfebrer** [comment]
Ok, now everything should work fine. You might want to change the name of the argument that I introduced on `read_basis` (`sort_by_fdf_appearance`) :sweat_smile:

**Comment by zerothi** [comment]
> Ok, now everything should work fine. You might want to change the name of the argument that I introduced on `read_basis` (`sort_by_fdf_appearance`) 😅

I'll probably revert that one, it should be handled differently, the whole idea of using species indices like that would be wrong...
Other parts of sisl uses `atoms` argument to pass a reference basis, here I would do the same (wait for it ;))

Ideally this issues should be resolved with some generic methods that resolves merges of geometries, atoms, orbitals, in a very strict manner, see e.g. #775.
This kind of procedure is used all-over, so it could be streamlined quite a bit I would assume.

**Comment by zerothi** [comment]
Thanks for discovering this!

Could you both try out the #779 branch? It should solve this problem (and more!). Also added some more tests.

**Comment by zerothi** [comment]
Closed via #779

**Pull request closed without merging**
