### PR TITLE
Added tiling and repeating to NamedIndex

### PR DESCRIPTION
**Pull request by jonaslb**
And Geometry tile and repeat makes use of it.
Tests were added as well.

### CODE REVIEW

**Comment by zerothi** [comment]
Similar to `NamedIndex.merge` the tiling and repeating could have some way of handling this.
There are various things that have not been cleared out in terms of `NamedIndex`, for instance if the names always follow a sub/remove etc. from a `Geometry`, then imagine doing:
```python
device = geom.cut(...).cut(...)
# at this point 'Left' is all atoms in device
device = device.tile(...).tile(...)
```
how should the final name-space look like? It isn't obvious what to do.
Again, I think that one user might expect one thing, while another might expect another. So I would also prefer some context handler in this case.

Also, I want to re-think the NamedIndex so it has an intuitive handling from the `Geometry` perspective. Currently it is highly irregular (as you have found! ;) )

**Comment by jonaslb** [comment]
I think as long as it is documented and consistent, users can (and should) adjust expectations. As long as naming isn't clearly misleading, but that's not the case here, I think.

And I'd rather be able to tile NamedIndex than not, which is the case currently. And I also think it'd be inelegant if Geometry didn't handle it.

Regarding a re-think: Perhaps one possibility would be to take some inspiration from CAD programs. How things are created is always a 'list of instructions' eg. "cylinder here, hole in it here, ...". So perhaps a `tile` operation could somehow result in a GeometryUnion object that contained references to its building blocks. Anyway, just ideas.

**Comment by zerothi** [comment]
> I think as long as it is documented and consistent, users can (and should) adjust expectations. As long as naming isn't clearly misleading, but that's not the case here, I think.

I don't think this is always the case. ;)
From experience people will be troubled if they get a result that is different from their expectations, regardless of documentation. Again, in this case there may be several *useful* outcomes. And choosing one or the other as the baseline in `Geometry.tile` is dangerous. Since 1) one user may be happy with the solution, 2) other users may not expect this and thus needs to revert what is happening, thus adding code, just as you need! In either case it is loose-loose.

This, I think, is a good example when not to add something to the code. Instead there could be a function implementing your said idea for the `Geometry` and then once we have a context handler which can deal with *all* expected situations it should be hard-coded.

As another example consider why `dict` does not have `__add__` implemented? It could easily be equal to `update`. But it isn't because of ambiguity, same applies here. They could have documented it and selected method, but decided not to since it creates ambiguity.

I really think that methods should be chosen with care. This I have learn over the years, and probably there are quite a few methods that should be removed from various classes!

> 
> And I'd rather be able to tile NamedIndex than not, which is the case currently. And I also think it'd be inelegant if Geometry didn't handle it.

I like your `NamedIndex` tile! I am just opposed to the `Geometry.tile` handling. For instance it would be very easy to have a method employing what you did:

```python
def geometry_name_tile(geometry, reps, axis):
    geom = geometry.tile(reps, axis)
    geom._names = geometry.names.tile(reps, len(geometry))
    return geom
```
Similarly with `repeat`.
> 
> Regarding a re-think: Perhaps one possibility would be to take some inspiration from CAD programs. How things are created is always a 'list of instructions' eg. "cylinder here, hole in it here, ...". So perhaps a `tile` operation could somehow result in a GeometryUnion object that contained references to its building blocks. Anyway, just ideas.

This is a great idea, and would solve lots of problems related to name-spaces of indices etc.

**Comment by jonaslb** [comment]
I don't think the comparison to dicts are on-point because sisl geometries are not equally generalized (they only handle geometries of atoms).

Regardless, I can remove the integration into `Geometry` to get this merged. What should the default behaviour be then? The previous behaviour was to delete the names, but was that by intension or an omission?

**Comment by zerothi** [comment]
> I don't think the comparison to dicts are on-point because sisl geometries are not equally generalized (they only handle geometries of atoms).

I have to disagree ;)
> 
> Regardless, I can remove the integration into `Geometry` to get this merged. What should the default behaviour be then? The previous behaviour was to delete the names, but was that by intension or an accidental omission?

It was by omission since they where never really intended for these use cases. What I think is the least invasive and expected output is that the indices are kept to retain the same ordering for `tile` and `repeat`.

**Comment by jonaslb** [comment]
I will close this because I'm not working on it any more.

**Pull request closed without merging**
