### PR TITLE
Brillouin zone xarray Dataset dispatch

### PR DESCRIPTION
**Pull request by pfebrer**
I was trying to parallelize a fatbands calculation using the `dataarray` dispatch. However I was failing because it looked something like this:

```python
weights_store = []

def _weights_from_eigenstate(eigenstate):

    weights = eigenstate.norm2(sum=False)
    weights_store.append(weights)
    return eigenstate.eig

bz.apply.dataarray.eigenstate(wrap=_weights_from_eigenstate)
```

and the problem was that `weights_store` was not available to the processes, so it ended up empty. Therefore, I realized that I needed to return everything at the wrapping function and let the dispatch handle it. I saw that the `dataarray` dispatch has some support for datasets, but it was not what I needed. The dispatch that I added can be used like this:

```python
import sisl
import numpy as np

# Construct a hamiltonian for graphene
gr = sisl.geom.graphene()
H = sisl.Hamiltonian(gr)
H.construct([(0.1, 1.44), (0, -2.7)])
# And a band structure
bz = sisl.BandStructure(H, [[0, 0, 0], [2/3, 1/3, 0], [1/2, 0, 0]], 9, ["Gamma", "M", "K"])

# The wrapping function to calculate weights
def _weights_from_eigenstate(eigenstate):
    """Function that will wrap the loop to calculate the fatbands weights"""
    weights = eigenstate.norm2(sum=False)
    
    return np.array((eigenstate.eig, *weights.real)).T

# And now run the calculation to get the dataset
dataset = bz.apply.dataset.eigenstate(
        coords=("band",), # The coordinates coming from the brillouin zone
        wrap=_weights_from_eigenstate, # The wrapping function to return all the values
        datavars=[
            "eigval", # First data in the array are the eigenvalues
            ("weight", "orb", int(bz.parent.no)), # After that, there are bz.parent.no chunks of data 
            # that contain information about the weights. It should all be packed into the same data variable
            # while adding the new "orb" coordinate
        ], 
)
```

which gives you:
```
<xarray.Dataset>
Dimensions:  (band: 2, k: 9, orb: 2)
Coordinates:
  * k        (k) int32 0 1 2 3 4 5 6 7 8
  * band     (band) int32 0 1
  * orb      (orb) int32 0 1
Data variables:
    eigval   (k, band) float64 -8.1 8.1 -7.774 7.774 ... -1.977 1.977 -2.7 2.7
    weight   (k, band, orb) float64 0.5 0.5 0.5 0.5 0.5 ... 0.5 0.5 0.5 0.5 0.5
Attributes:
    bz:       BandStructure{nk: 9,\n SuperCell{nsc: [3 3 1],\n  A=[2.130, 1.2...
    parent:   Hamiltonian{non-zero: 8, orthogonal: True,\n Spin{unpolarized, ...
```

and (the reason why I did this) the same calculation can be done in parallel now:
```python
with bz.apply.renew(pool=True) as parallel:
    dataset = parallel.dataset.eigenstate(
        coords=("band",), datavars=["eigval", ("weight", "orb", int(bz.parent.no))], 
        wrap=_weights_from_eigenstate
    )
```

Let me know if you think it could be useful (you can also reimplement it to make it better, I don't care as long as it has the same functionality). Otherwise I can register it in the fatbands plot of course, that's the beauty of dispatchers :), but I thought it might be useful in other cases as well.

Cheers!

### CODE REVIEW

**Comment by pfebrer** [comment]
Nevermind for now, I think this can be made more intuitive with a different implementation. But I'd like to focus on merging https://github.com/zerothi/sisl/pull/312 first

**Comment by zerothi** [comment]
I believe this can already be done with:
```
d = band_struct.apply.renew(unzip=True).xarray.eigenstate(wrap=wrap, coords=[('eig',), ("band", "orb")])
```
?

**Comment by zerothi** [comment]
But, yes, currently one cannot name the variables, I'll have to amend the `xarray` class here. Would this work?

**Comment by zerothi** [comment]
Oh, actually

```python
def wrap(es):
    return es.eig, es.norm2(sum=False)
d = band_struct.apply.renew(unzip=True).xarray.eigenstate(wrap=wrap, coords=['eig', ("band", "orb")], name=['eigenstate', 'norm2'])
```
already works in the latest commit (the latest commit allows `'eig'` rather than `('eig',)`)

**Comment by pfebrer** [comment]
Great! Thank you, that totally works! Somehow I was playing with unzip but didn't manage to get this behavior.

**Pull request closed without merging**
