### PR TITLE
mnt: changed all root_fdf to fdf

### PR DESCRIPTION
**Pull request by zerothi**
@pfebrer could you please see if everything is ok by doing this?

I reran the tests, and all seems to pass on my comp, but I don't know how you test it?

### CODE REVIEW

**Comment by pfebrer** [comment]
Looks good to me! Although I was already fixing this in https://github.com/zerothi/sisl/pull/446 :sweat_smile:  But it's great that you had the time to look at the code in sisl.viz :)

By the way, the documentation is automatically updated using the parameters of each plot class with `python -m sisl.viz._doc_updater` (as explained in that file). But even that will probably change.

I wouldn't bother too much at modifying the current `sisl.viz` module as most things will change to make it more modular and hopefully everything will be easier to understand :) So I wouldn't push this to `main` as it would probably create unnecessary conflicts with the other PR.

**Comment by zerothi** [comment]
Ok! I'll close!

**Comment by pfebrer** [comment]
Sorry :)

**Comment by zerothi** [comment]
No worries! :)

**Pull request closed without merging**
