### PR TITLE
Support for xarray in read_scf outSile

### PR DESCRIPTION
**Pull request by pfebrer96**
The pull request that comes from https://github.com/zerothi/sisl/issues/175.

### CODE REVIEW

**Comment by zerothi** [comment]
See latest comment in #175

**Comment by pfebrer96** [comment]
I'm opened a new PR: https://github.com/zerothi/sisl/pull/188, I rebased my branch and apparently messed it up, sorry.

**Comment by zerothi** [comment]
When creating a new PR, start over. Don't take over work from other branches ;)
I'll try and fix it.

**Comment by pfebrer96** [comment]
What do you mean, is there something wrong with https://github.com/zerothi/sisl/pull/188?

**Comment by zerothi** [comment]
> I opened a new PR: #188, I rebased my branch and apparently messed it up, sorry.

Sorry, I initially thought your #188 was a rebase + additional work. It seems you did it correctly ;)
Thanks!

**Pull request closed without merging**
