### PR TITLE
Included missing notebook in the viz docs

### PR DESCRIPTION
**Pull request by pfebrer**
I don't know why, but there was a notebook that was not included in the `.rst` file (probably I forgot to include it).

### CODE REVIEW

**Comment by pfebrer** [comment]
Thanks! Could you refresh the documentation? I'm writing a message on discord to advertise the new `sisl.viz` :)

**Comment by zerothi** [comment]
Is it important to get out now? It could be great to get #629 in as well? Shouldn't take too much

**Comment by pfebrer** [comment]
Hmm ok, I'll just save the message

**Comment by zerothi** [comment]
I am quite worried about my limits on the CI's, not infrequently I get emails on having runned too much :)
That is why I am trying to limit *unnecessary* runs. Hope you understand!
(you can print it here for safe keeping? )

**Comment by pfebrer** [comment]
In the case of documentation I think it would be worth to have some caching, specially of the executed notebooks. (the hardest point would be to keep track of which parts of sisl the notebook depends on)

**Comment by zerothi** [comment]
Agreed, I haven't had time to look into GA caching... But that would indeed be great!

**Pull request merged**
